### ISSUE TITLE
Config check handler is defined, but never used.

### ISSUE THREAD

**Issue by MaximF** [geerlingguy/ansible-role-nginx#122]
"validate nginx configuration" handler is defined but is never used in the code.

https://github.com/geerlingguy/ansible-role-nginx/blob/7aa2ea4779e4bd28c0f5a94489464e4da6f76049/handlers/main.yml#L5-L7

Worth to remove?

**Comment by geerlingguy** [comment]
Maybe so; it was originally used prior to restarting nginx on config changes, but that seemed to cause some issue with SELinux. I'm completely lacking the context anymore, but I am seeing that _I_ don't use it in any of my playbooks, so I'm not too worried about dropping it... It would have to go into at least a minor version bump though, since it would be removing existing functionality someone _might_ be using.

**Comment by MaximF** [comment]
Thank for following up @geerlingguy 
I was trying to create a PR to remove it, but seems like your repo isn't accepting public PRs.

**Comment by bew** [comment]
I was about to open an issue and a PR about adding the validation step just after creating the config file (using the `validate` key of the `template` action), do you still want to remove it?
If so, how would I go about checking that the config is correct after the template pass, and before trying to restart nginx?
