### ISSUE TITLE
Ubuntu PPA seems to not be maintained that much... switch to nginx packages?

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-nginx#202]
See: http://nginx.org/en/linux_packages.html#Ubuntu

The Ubuntu PPA this role currently uses doesn't support 20.04 at all, and seems to be maintained sporadically at best.

**Comment by geerlingguy** [comment]
A couple options: use system packages (can lag nginx stable), like we do for debian, or incorporate the deb repo from nginx directly.

**Comment by geerlingguy** [comment]
Not a high priority since `nginx_ppa_use: false` is the default... but it might be worth doing.

**Comment by colinodell** [comment]
The versions of nginx available in that old PPA have known security vulnerabilities.

It looks like nginx now maintains their own apt repository which does have up-to-date versions: https://www.nginx.com/resources/wiki/start/topics/tutorials/install/#official-debian-ubuntu-packages  I'd recommend changing `nginx_ppa_use: true` to use that instead of the old, unmaintained PPA.
