### ISSUE TITLE
Debian nginx_default_vhost_path is included in nginx.conf

### ISSUE THREAD

**Issue by jyrkij** [geerlingguy/ansible-role-nginx#30]
`nginx.conf` includes two globs:

- `include /etc/nginx/conf.d/*.conf;`
- `include /etc/nginx/sites-enabled/*.conf;`

`nginx_default_vhost_path` is `.../default` on Debian thus it is not included by either of the includes. There should probably be a line including `nginx_default_vhost_path` if it is not scheduled for removal.

**Comment by geerlingguy** [comment]
The default vhost should be inside `/etc/nginx/sites-enabled/` (if it's active...). I'm not seeing the issue here? If you set `nginx_remove_default_vhost` to `true` and run the role, the symlink in -enabled will be removed. If you want to add it back in, you'd need to do that separately, or rebuild the server with `nginx_remove_default_vhost: false`.
