### ISSUE TITLE
Validation of nginx.conf fails if it have includes of pre-defined files (like fastcgi_params)

### ISSUE THREAD

**Issue by strangeman** [geerlingguy/ansible-role-nginx#39]
If nginx.conf or vhosts.conf have ```include fastcgi_params;```, ansible fails on line 29 in tasks/main.yml (```validate: 'nginx -t -c %s'```)

```TASK: [geerlingguy.nginx | Copy nginx configuration in place.] **************** 
failed: [flugertest] => {"failed": true}
msg: failed to validate: rc:1 error:nginx: [emerg] open() "/root/.ansible/tmp/ansible-tmp-1452489701.48-215325050721011/fastcgi_params" failed (2: No such file or directory) in /etc/nginx/sites-enabled/vhosts.conf:29
nginx: configuration file /root/.ansible/tmp/ansible-tmp-1452489701.48-215325050721011/source test failed```

I suggest to remove this validation, because we already validate nginx configuration via handler.

**Comment by geerlingguy** [comment]
Another quick fix: you can use the full path to the fastcgi_params file (e.g. `include /etc/nginx/fastcgi_params` or something like that). I'll take a look later (want to make sure the validation in the restart handler would be adequate... I think we added the template validation because otherwise the configuration could end up in a broken state in other cases).

**Comment by strangeman** [comment]
Okay, thank you.

**Comment by opdavies** [comment]
> Another quick fix: you can use the full path to the fastcgi_params file (e.g. include /etc/nginx/fastcgi_params or something like that)

This is what I had to do. I thought that it was odd though, having not needed to do that with Nginx before - at least now I know that it's due to the role.

**Comment by geerlingguy** [comment]
See #42 — this should no longer be an issue.
