### ISSUE TITLE
Task 'Define nginx_user.' skipped

### ISSUE THREAD

**Issue by Caroga** [geerlingguy/ansible-role-nginx#43]
Defining the nxing_user is skipped even though the variable is defined in both `defaults/main.yml` and the `playbook.yml`

```
TASK [geerlingguy.nginx : Define nginx_user.] **********************************
skipping: [010php.vm]
```

This occurs on a debian based system. I may be able to provide a PR if I got the time.

**Comment by rossedman** [comment]
@Caroga I think #41 is related to this as well. I am noticing that `nginx_user` isn't getting set properly in the `nginx.conf.j2` in RHEL. What version of Ansible are you using?

**Comment by rossedman** [comment]
Here is an example output on RHEL. Notice it loads the OS specific variables correctly, and identifies the OS, but then nginx_user is set incorrectly

```
TASK [geerlingguy.nginx : Include OS-specific variables.] **********************
task path: /Users/redata425/Sites/devops/vsphere/consul/roles/geerlingguy.nginx/tasks/main.yml:3
ok: [mconsul] => {"ansible_facts": {"__nginx_user": "nginx", "nginx_conf_path": "/etc/nginx/conf.d", "nginx_default_vhost_path": "/etc/nginx/conf.d/default.conf", "nginx_vhost_path": "/etc/nginx/conf.d"}, "changed": false, "invocation": {"module_args": {"_raw_params": "RedHat.yml"}, "module_name": "include_vars"}}

TASK [geerlingguy.nginx : debug] ***********************************************
task path: /Users/redata425/Sites/devops/vsphere/consul/roles/geerlingguy.nginx/tasks/main.yml:6
ok: [mconsul] => {
    "msg": "RedHat"
}

TASK [geerlingguy.nginx : Define nginx_user.] **********************************
task path: /Users/redata425/Sites/devops/vsphere/consul/roles/geerlingguy.nginx/tasks/main.yml:8
skipping: [mconsul] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [geerlingguy.nginx : debug] ***********************************************
task path: /Users/redata425/Sites/devops/vsphere/consul/roles/geerlingguy.nginx/tasks/main.yml:13
ok: [mconsul] => {
    "msg": "www-data"
}
```

**Comment by geerlingguy** [comment]
@Caroga / @rossedman - This sounds like an upstream issue...

The reason that task is skipped is somewhere, upstream of this role (e.g. in your playbook, in an included vars file, in an inventory somewhere), the `nginx_user` variable is being defined as `www-data`.

This role does not define `nginx_user` anywhere—not in `defaults/main.yml` nor in `vars/[os-family].yml`. It only defines `__nginx_user: "www-data"`, so that task will only be skipped if the playbook/inventory/vars you have configured are explicitly setting:

```
nginx_user: www-data
```

**Comment by geerlingguy** [comment]
@rossedman - You can even see that when the OS-specific variables are included—in your case `RedHat.yml`, it's picking up `"__nginx_user": "nginx"`, meaning it defaults to the user `nginx`.

When it hits the `Define nginx_user` task, it checks for whether `nginx_user` is already defined, and it says that it is, so it skips the task and uses the value you set upstream (in your playbook or inventory).

**Comment by rossedman** [comment]
@geerlingguy I thought the same thing, so I removed all roles and tasks and tried to only run this role. The only way I could fix it was explicitly setting `nginx_user` in my playbook. I also did a `find` and could not locate anywhere that `www-data` was being set.

**Comment by geerlingguy** [comment]
@rossedman - According to my local testing and also the automated tests for this role (https://travis-ci.org/geerlingguy/ansible-role-nginx/builds/104118511#L461), the task runs correctly when `nginx_user` isn't defined, so could it be an external inventory source?

Are you using dynamic inventory, or are you using some sort of deployment system, or do you control a static inventory file and the playbook you're running end-to-end? Dynamic inventory might be set to inject an `nginx_user`, and maybe it was set up originally to run on only Debian systems.

**Comment by rossedman** [comment]
@geerlingguy Dynamic inventory but it shouldn't be setting any of these variables because its coming from Terraform and all that is being defined is `ssh_user` and `ip_address`. I believe you though! You are the man. I will look into my side some more. I'm also using Ansible 2.0 so I was worried there was a change in the way facts were set in playbooks from dynamically loaded files. I thought they changed the priority on how those loaded.

**Comment by geerlingguy** [comment]
@rossedman - Hmm... I haven't messed with Terraform much, but I'm wondering if there's something upstream that's setting the variable or otherwise caching it. To test things out, try creating a local VM with Vagrant, and see if you can reproduce the issue; you can even use the LEMP example here for testing: https://github.com/geerlingguy/ansible-vagrant-examples/tree/master/lemp

**Comment by rbarabas** [comment]
I had the same problem when a different ansible role (let it be nameless for now) which first tried to pull in franklinkim's nginx first before this one. That role set a default value for "nginx_user" in its main.yml and from that moment on the variable remained set for even the successive (this) role. Not sure if this is related to inheritance upon dependencies. The problematic piece there was:

```
dependencies:
  - { role: franklinkim.nginx, when: consul_install_nginx == true and ansible_os_family == "Debian" }
  - { role: geerlingguy.nginx, when: consul_install_nginx == true and ansible_os_family == "RedHat" }
  - { role: joshualund.golang, when: consul_install_consul_cli == true }
```

**Comment by rbarabas** [comment]
I have opened an issue for the consumer role that exhibits this issue (you can find a reference to it above;)).

**Comment by rossedman** [comment]
@rbarabas This was the same role I was working with. I install my roles locally, so I removed the franklinkim one and I still had the problem. So I assumed it was here but maybe that isn't the case.

**Comment by rbarabas** [comment]
Are you sure the dependency wasn't pulled down again? 

Btw, setting nginx_user explicitly in the play will have higher priority so that should work as a workaround but it may not be the best workaround when you have a hybrid set of servers. Also, if you rename the variable in default/main.yml of franklinkim's nginx you should be able to proceed without an error. At least I was able to.

**Comment by rossedman** [comment]
@rbarabas I need to test again. It was pretty late when I did this, so I could be wrong. I did end up explicitly setting `nginx_user` which solved the problem but my main concern was Ansible 2.0 changing how files were loaded. I thought I read something about how that had changed.

**Comment by Caroga** [comment]
wow, i've been away for some days and really missed a good convo here!

Anyhow, 
To see the roles and setup I've used: https://github.com/010PHP/010php.nl/tree/master/build
```
[caroga@lockhead ~]$ ansible --version
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

**Comment by Caroga** [comment]
Also, I've tried placing it inside the playbook.yml, which should (as stated earlier) have a higher priority over the rest. `https://github.com/010PHP/010php.nl/blob/master/build/playbook.yml`

**Comment by rossedman** [comment]
@Caroga Didn't mean to highjack your thread. Thought these issues were related. :)

**Comment by Caroga** [comment]
Never a problem, all discussion helps!
