### ISSUE TITLE
Add tags ?

### ISSUE THREAD

**Issue by ahivert** [geerlingguy/ansible-role-nginx#57]
Why not add some tags to improve the time to launch a playbook ?

Like :
- nginx
- nginx setup
- nginx conf 
...

**Comment by geerlingguy** [comment]
I generally use tags on a role-by-role basis, as managing/adding tags task-by-task makes for much longer files and (for me, at least) only provides marginal gains. If a particular role gets to take too long during idempotent runs (e.g. 2nd run and so on), then I typically split up the role instead of use tags to make parts of the role runnable.
