### ISSUE TITLE
Add SELinux Rules On Red Hat Systems?

### ISSUE THREAD

**Issue by leifmadsen** [geerlingguy/ansible-role-nginx#64]
Just wondering if it seems appropriate to add the SELinux rules to permit nginx to be used without modification / post-task with Red Hat systems that have SELinux enabled?

Or does it seem more appropriate to let people manage that outside of the role itself? I could add a PR if it seems appropriate. I'd just add it to the setup-RedHat.yml probably, and then make it optional via a flag (default: false to match current resulting deploy).

**Comment by geerlingguy** [comment]
I would rather have that managed outside the role itself, since it's a more RHEL-centric configuration that (imo) should be managed comprehensively either in its own role or on a per-playbook basis.

If I were maintaining roles that were RHEL-only, I would do it differently, but since the majority of this role's users skew Debian/Ubuntu, I'd rather not maintain SELinux functionality within this role.

**Comment by leifmadsen** [comment]
I tend to agree. Thanks for the quick response!
