### ISSUE TITLE
Support for HTTP Auth

### ISSUE THREAD

**Issue by Cyberkini** [geerlingguy/ansible-role-nginx#89]
It would be a great feature, if you could control HTTP Authentication with this role, without writing an extension role for doing this. For example, if you could state a user : password variable and the role would automatically create the .htpasswd file and include it in the vhost on "location /".

**Comment by geerlingguy** [comment]
@Cyberkini - Thanks for the issue! I actually have had the same question for my Apache role (see https://github.com/geerlingguy/ansible-role-apache/pull/63#issuecomment-266044966), and my answer is the same here—since this isn't an 80% use case, and I'd like to keep this role focused on Nginx setup and config (and less on individual use cases for host configurations, especially non-prod use cases), I'd rather someone creates a separate role just for setting up basic auth (maybe one that works universally with Nginx and Apache, that'd be awesome).
